### PR TITLE
omolola odunlami

### PR DESCRIPTION
**Pull request by Odunlola**

### CODE REVIEW

**Comment by Julio-Leon** [comment]
Unfortunately this file is not running properly, it seems that you misspelled some stuff, and also added some uncommented code.

Please let me know if you have any questions!

Homework 4: Incomplete for now, please feel free to resubmit!

Current Homework Completion Percentage: 50%

**Comment by katiemcmillin** [comment]
HI Lola,
Thank you for the resubmission. I could see from the commented out code in your commits how hard you worked on this. I made a few suggestions to arrive at the correct print output for the only two questions that didn't have the right print values when I ran the file. Please let me know if you have any questions. Marked complete!
 
Question 3:
The logic was close. If you have some time to mess around with this, try placing console.logs and see what your original code was printing out to see what's going on.
function isAVowel(letter) {
  const vowels = ["a", "e", "i", "o", "u"];
  for (let char in vowels) {
    if (letter === char) {
      return true;
    }
  }
  return false;
}

Question 6.2 printPrimes:
This question was asking to print the prime numbers up to num.
function printPrimes(num) {
  for (let i = 2; i <= num; i++) {
    if (checkPrime(i)) {
      console.log(i);
    }
  }
}

**Comment by Odunlola** [comment]
well noted. Thank you

**Comment by Odunlola** [comment]
Thank you Katie, I’ll work thes out on my own and reprint output.

**Pull request closed without merging**
